FROM node:alpine
LABEL maintainer="jose.duran@duransoftware.es"
LABEL description="Device retection api"
LABEL version="0.1.0"

RUN mkdir /app
RUN mkdir /app/swagger
RUN mkdir /app/node_modules

WORKDIR .

	ADD ./docker/DsDeviceDetection.js ./app/ 
	ADD ./docker/swagger/ ./app/swagger/
	ADD node_modules/ ./app/node_modules/


WORKDIR ./app

RUN ls -la /app/*

EXPOSE 51235
CMD ["node", "DsDeviceDetection"]
